title: <p align="center"> Seung Pang </p>
logo: "headshot.png?raw=true" 
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/seung-p-094195105/">LinkedIn</a> |
  <a href="https://github.com/SeungPang11">GitHub</a>
  </p>
  <p align="justify">
  Master's in Computer Science from New York University. 
  </p>
  
theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
