title: Seung Pang 
<img src="headshot.png?raw=true" alt="Seung Pang" width="50"/>
# logo: "headshot.png?raw=true" 
description: 
  <p align="left">
   MS in Computer Science @New York University 
  </p>
  
theme: jekyll-theme-minimal
