title: Seung Pang 
logo: "headshot.png?raw=true" 
description: 
  <p align="left">
  [![LinkedIn](https://img.shields.io/badge/LinkedIn-blue)](www.linkedin.com/in/seung-p-094195105/) |
  [![GitHub](https://img.shields.io/badge/GitHub-blue?logo=GitHub)](https://github.com/SeungPang11)
   MS in Computer Science from New York University | 
   Experience in Data Science/ Analytics, ML, Data Engineering | 
   Currently working towards AWS Certificate
  </p>
  
theme: jekyll-theme-minimal
