title: Seung Pang
logo: headshot.png 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Master's in Computer Science from New York University. 
  <br><br>
  Courses: Big Data, Mining Massive Datasets, Machine Learning, <br>
  Principle of Databases Systems, Information Visualization, <br>
  Design & Analysis of Algorithms
  <br><br>
  <a href="https://www.linkedin.com/in/seung-p-094195105/">View my LinkedIn Profile</a> 
#show_downloads: true
theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
