title: Seung Pang 
logo: "headshot.png?raw=true" 
description: 
  <p align="left">
   MS in Computer Science from New York University | 
   Experience in Data Science/ Analytics, ML, Data Engineering | 
  </p>
  
theme: jekyll-theme-minimal
