title: Seung Pang 
logo: "headshot.png?raw=true" 
description: 
  <p align="center">
 [![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/seung-p-094195105/)
  <a href="https://www.linkedin.com/in/seung-p-094195105/">LinkedIn</a> 
  <a href="https://github.com/SeungPang11">GitHub</a>
  </p>
  <p align="justify">
  Master's in Computer Science from New York University. 
  </p>
  
theme: jekyll-theme-minimal
